---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.3
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - "recipe[apt::default]"
      - "recipe[build-essential::default]"
      - "recipe[vulnpryer::default]"
    attributes:
      vulnpryer:
        config:
          vulndb:
            consumer_key:     bar
            consumer_secret:  foo
          redseal:
            username:         bar
            password:         foo
